### ISSUE TITLE
v2.6.42 mode tunnel using IKEv2 no tunnels up

### ISSUE THREAD

**Issue by somme8023** [xelerance/Openswan#232]
Hello,

With the following configuration, the tunnel can not get up.Why?

**Cisco route config:**
crypto ikev2 proposal policy 
 encryption 3des
 integrity md5
 group 2  
!         
crypto ikev2 policy policy 
 proposal policy
!         
crypto ikev2 keyring key
 peer openswan
  address 172.16.99.120
  pre-shared-key cisco
 !               
crypto ikev2 profile profile
 match identity remote address 172.16.99.120 255.255.0.0 
 identity local address 172.16.5.245
 authentication remote pre-share
 authentication local pre-share
 keyring local key
!              
crypto ipsec transform-set tran esp-3des esp-md5-hmac 
 mode tunnel
!             
crypto map ikev2map 10 ipsec-isakmp 
 set peer 172.16.99.120
 set transform-set tran 
 set ikev2-profile profile
 match address vpn
!         
!           
interface FastEthernet0/0
 ip address 172.16.5.245 255.255.0.0
 ip nat outside
 speed auto
 duplex auto
 crypto map ikev2map
!         
interface FastEthernet0/1
 ip address 192.168.80.1 255.255.255.0
 ip nat inside
 speed auto
 duplex auto
!         
ip nat inside source list 100 interface FastEthernet0/0 overload
ip forward-protocol nd
!         
!         
no ip http server
no ip http secure-server
ip route 0.0.0.0 0.0.0.0 172.16.99.120
!         
ip access-list extended vpn
 permit ip 192.168.80.0 0.0.0.255 192.168.0.0 0.0.0.255

**Device configuration：**
/etc # cat ipsec.config
/etc/ipsec.conf - Openswan IPsec configuration file

version 2.0     # conforms to second version of ipsec.conf specification

config setup
   dumpdir=/var/run/pluto/
   nat_traversal=yes
   oe=off
   protostack=netkey
   keep_alive=60
   plutodebug=none

conn IPSec_TUN_1
   type=tunnel

   #SA configuration
   pfs=no
   phase2=esp
   phase2alg=3des-md5
   salifetime=28800s
   dpdaction=restart_by_peer
   dpddelay=60
   dpdtimeout=180

   #IKE configuration
   authby=secret
   ike=3des-md5;modp1024
   ikelifetime=86400s

   #Left configuration
   left=172.16.99.120
   leftsubnet=192.168.0.0/24
   leftnexthop=172.16.5.1
   leftid=172.16.99.120
   leftupdown="ipsec_updown 1"

   #Right configuration
   right=172.16.5.245
   rightsubnet=192.168.80.0/24
   rightid=172.16.5.245
   ikev2=propose

   auto=start

/etc # cat ipsec.secrets 
172.16.99.120 172.16.5.245: PSK "cisco"

**View IPSec information on device：**
/etc # /usr/scripts/ipsec start
ipsec_setup: Starting Openswan IPsec U2.6.42/K3.10.49...
/etc # pluto[3264]: Starting Pluto (Openswan Version 2.6.42; Vendor ID OSWQbJPI|p_a) pid:3264
pluto[3264]: LEAK_DETECTIVE support [disabled]
pluto[3264]: OCF support for IKE [disabled]
pluto[3264]: SAref support [disabled]: Protocol not available
pluto[3264]: SAbind support [disabled]: Protocol not available
pluto[3264]: NSS support [disabled]
pluto[3264]: HAVE_STATSD notification support not compiled in
pluto[3264]: Setting NAT-Traversal port-4500 floating to on
pluto[3264]:    port floating activation criteria nat_t=1/port_float=1
pluto[3264]:    NAT-Traversal support  [enabled]
pluto[3264]: using /dev/urandom as source of random entropy
pluto[3264]: ike_alg_register_enc(): Activating OAKLEY_AES_CBC: Ok (ret=0)
pluto[3264]: ike_alg_register_hash(): Activating OAKLEY_SHA2_512: Ok (ret=0)
pluto[3264]: ike_alg_register_hash(): Activating OAKLEY_SHA2_256: Ok (ret=0)
pluto[3264]: starting up 1 cryptographic helpers
pluto[3264]: started helper pid=3266 (fd:5)
pluto[3264]: Using Linux XFRM/NETKEY IPsec interface code on 3.10.49
pluto[3266]: using /dev/urandom as source of random entropy
pluto[3264]: ike_alg_register_enc(): Activating aes_ccm_8: Ok (ret=0)
pluto[3264]: ike_alg_add(): ERROR: algo_type '0', algo_id '0', Algorithm type already exists
pluto[3264]: ike_alg_register_enc(): Activating aes_ccm_12: FAILED (ret=-17)
pluto[3264]: ike_alg_add(): ERROR: algo_type '0', algo_id '0', Algorithm type already exists
pluto[3264]: ike_alg_register_enc(): Activating aes_ccm_16: FAILED (ret=-17)
pluto[3264]: ike_alg_add(): ERROR: algo_type '0', algo_id '0', Algorithm type already exists
pluto[3264]: ike_alg_register_enc(): Activating aes_gcm_8: FAILED (ret=-17)
pluto[3264]: ike_alg_add(): ERROR: algo_type '0', algo_id '0', Algorithm type already exists
pluto[3264]: ike_alg_register_enc(): Activating aes_gcm_12: FAILED (ret=-17)
pluto[3264]: ike_alg_add(): ERROR: algo_type '0', algo_id '0', Algorithm type already exists
pluto[3264]: ike_alg_register_enc(): Activating aes_gcm_16: FAILED (ret=-17)
pluto[3264]: added connection description "IPSec_TUN_1"
pluto[3264]: listening for IKE messages
pluto[3264]: adding interface lan0/lan0 192.168.0.1:500
pluto[3264]: adding interface lan0/lan0 192.168.0.1:4500
pluto[3264]: adding interface wan/wan 172.16.99.120:500
pluto[3264]: adding interface wan/wan 172.16.99.120:4500
pluto[3264]: adding interface lo/lo 127.0.0.1:500
pluto[3264]: adding interface lo/lo 127.0.0.1:4500
pluto[3264]: loading secrets from "/etc/ipsec.secrets"
pluto[3264]: "IPSec_TUN_1" #1: initiating v2 parent SA
pluto[3264]: "IPSec_TUN_1" #1: transition from state STATE_IKEv2_START to state STATE_PARENT_I1
pluto[3264]: "IPSec_TUN_1" #1: STATE_PARENT_I1: sent v2I1, expected v2R1
pluto[3264]: "IPSec_TUN_1" #2: transition from state STATE_PARENT_I1 to state STATE_PARENT_I2
pluto[3264]: "IPSec_TUN_1" #2: STATE_PARENT_I2: sent v2I2, expected v2R2 {auth=IKEv2 cipher=oakley_3des_cbc_192 integ=md5_96 prf=oakley_md5 group=modp1024}
pluto[3264]: packet from 172.16.5.245:500: IKEv2 mode peer ID is ID_IPV4_ADDR: '172.16.5.245'
pluto[3264]: | Checking TSi(1)/TSr(1) selectors, looking for exact match
pluto[3264]: | printing contents struct traffic_selector
pluto[3264]: |   ts_type: IKEv2_TS_IPV4_ADDR_RANGE
pluto[3264]: |   ipprotoid: 0
pluto[3264]: |   startport: 0
pluto[3264]: |   endport: 65535
pluto[3264]: |   ip low: 192.168.0.0
pluto[3264]: |   ip high: 192.168.0.255
pluto[3264]: | printing contents struct traffic_selector
pluto[3264]: |   ts_type: IKEv2_TS_IPV4_ADDR_RANGE
pluto[3264]: |   ipprotoid: 0
pluto[3264]: |   startport: 0
pluto[3264]: |   endport: 65535
pluto[3264]: |   ip low: 192.168.80.0
pluto[3264]: |   ip high: 192.168.80.255
pluto[3264]: "IPSec_TUN_1" #2: transition from state STATE_PARENT_I2 to state STATE_PARENT_I3
pluto[3264]: "IPSec_TUN_1" #2: negotiated tunnel [192.168.0.0,192.168.0.255:0-65535 0] -> [192.168.80.0,192.168.80.255:0-65535 0]
pluto[3264]: "IPSec_TUN_1" #2: STATE_PARENT_I3: PARENT SA established tunnel mode {ESP=>0x7bb07847 <0x81302d8a xfrm=3DES_192-HMAC_MD5 NATOA=none NATD=none DPD=none}
pluto[3264]: | releasing whack for #2 (sock=-1)
pluto[3264]: | releasing whack for #1 (sock=-1)

/etc # /usr/local/sbin/ipsec auto --status
000 using kernel interface: netkey
000 interface lo/lo 127.0.0.1
000 interface lo/lo 127.0.0.1
000 interface wan/wan 172.16.99.120
000 interface wan/wan 172.16.99.120
000 interface lan0/lan0 192.168.0.1
000 interface lan0/lan0 192.168.0.1
000 %myid = (none)
000 debug none
000 
000 virtual_private (%priv):
000 - allowed 0 subnets: 
000 - disallowed 0 subnets: 
000 WARNING: Either virtual_private= is not specified, or there is a syntax 
000          error in that line. 'left/rightsubnet=vhost:%priv' will not work!
000 WARNING: Disallowed subnets in virtual_private= is empty. If you have 
000          private address space in internal use, it should be excluded!
000 
000 algorithm ESP encrypt: id=2, name=ESP_DES, ivlen=8, keysizemin=64, keysizemax=64
000 algorithm ESP encrypt: id=3, name=ESP_3DES, ivlen=8, keysizemin=192, keysizemax=192
000 algorithm ESP encrypt: id=12, name=ESP_AES, ivlen=8, keysizemin=128, keysizemax=256
000 algorithm ESP encrypt: id=14, name=ESP_AES_CCM_A, ivlen=8, keysizemin=128, keysizemax=256
000 algorithm ESP encrypt: id=15, name=ESP_AES_CCM_B, ivlen=8, keysizemin=128, keysizemax=256
000 algorithm ESP encrypt: id=16, name=ESP_AES_CCM_C, ivlen=8, keysizemin=128, keysizemax=256
000 algorithm ESP encrypt: id=18, name=ESP_AES_GCM_A, ivlen=8, keysizemin=160, keysizemax=288
000 algorithm ESP encrypt: id=19, name=ESP_AES_GCM_B, ivlen=12, keysizemin=160, keysizemax=288
000 algorithm ESP encrypt: id=20, name=ESP_AES_GCM_C, ivlen=16, keysizemin=160, keysizemax=288
000 algorithm ESP auth attr: id=1, name=AUTH_ALGORITHM_HMAC_MD5, keysizemin=128, keysizemax=128
000 algorithm ESP auth attr: id=2, name=AUTH_ALGORITHM_HMAC_SHA1, keysizemin=160, keysizemax=160
000 algorithm ESP auth attr: id=5, name=AUTH_ALGORITHM_HMAC_SHA2_256, keysizemin=256, keysizemax=256
000 algorithm ESP auth attr: id=6, name=AUTH_ALGORITHM_HMAC_SHA2_384, keysizemin=384, keysizemax=384
000 algorithm ESP auth attr: id=7, name=AUTH_ALGORITHM_HMAC_SHA2_512, keysizemin=512, keysizemax=512
000 
000 algorithm IKE encrypt: id=0, name=(null), blocksize=16, keydeflen=131
000 algorithm IKE encrypt: id=5, name=OAKLEY_3DES_CBC, blocksize=8, keydeflen=192
000 algorithm IKE encrypt: id=7, name=OAKLEY_AES_CBC, blocksize=16, keydeflen=128
000 algorithm IKE hash: id=1, name=OAKLEY_MD5, hashsize=16
000 algorithm IKE hash: id=2, name=OAKLEY_SHA1, hashsize=20
000 algorithm IKE hash: id=4, name=OAKLEY_SHA2_256, hashsize=32
000 algorithm IKE hash: id=6, name=OAKLEY_SHA2_512, hashsize=64
000 algorithm IKE dh group: id=2, name=OAKLEY_GROUP_MODP1024, bits=1024
000 algorithm IKE dh group: id=5, name=OAKLEY_GROUP_MODP1536, bits=1536
000 algorithm IKE dh group: id=14, name=OAKLEY_GROUP_MODP2048, bits=2048
000 algorithm IKE dh group: id=15, name=OAKLEY_GROUP_MODP3072, bits=3072
000 algorithm IKE dh group: id=16, name=OAKLEY_GROUP_MODP4096, bits=4096
000 algorithm IKE dh group: id=17, name=OAKLEY_GROUP_MODP6144, bits=6144
000 algorithm IKE dh group: id=18, name=OAKLEY_GROUP_MODP8192, bits=8192
000 algorithm IKE dh group: id=22, name=OAKLEY_GROUP_DH22, bits=1024
000 algorithm IKE dh group: id=23, name=OAKLEY_GROUP_DH23, bits=2048
000 algorithm IKE dh group: id=24, name=OAKLEY_GROUP_DH24, bits=2048
000 
000 stats db_ops: {curr_cnt, total_cnt, maxsz} :context={0,3,36} trans={0,3,540} attrs={0,3,720} 
000 
000 "IPSec_TUN_1": 192.168.0.0/24===172.16.99.120<172.16.99.120>---172.16.5.1...172.16.5.245<172.16.5.245>===192.168.80.0/24; erouted; eroute owner: #2
000 "IPSec_TUN_1":     myip=unset; hisip=unset; myup=ipsec_updown 1;
000 "IPSec_TUN_1":   ike_life: 86400s; ipsec_life: 28800s; rekey_margin: 540s; rekey_fuzz: 100%; keyingtries: 0 
000 "IPSec_TUN_1":   policy: PSK+ENCRYPT+TUNNEL+UP+IKEv2ALLOW+IKEv2Init+SAREFTRACK+lKOD+rKOD; prio: 24,24; interface: wan; 
000 "IPSec_TUN_1":   dpd: action:restart_by_peer; delay:60; timeout:180;  
000 "IPSec_TUN_1":   newest ISAKMP SA: #1; newest IPsec SA: #2; 
000 "IPSec_TUN_1":   IKE algorithms wanted: 3DES_CBC(5)_000-MD5(1)_000-MODP1024(2); flags=-strict
000 "IPSec_TUN_1":   IKE algorithms found:  3DES_CBC(5)_192-MD5(1)_128-MODP1024(2)
000 "IPSec_TUN_1":   IKE algorithm newest: BLOWFISH_CBC_192-MD5-MODP1024
000 "IPSec_TUN_1":   ESP algorithms wanted: 3DES(3)_000-MD5(1)_000; flags=-strict
000 "IPSec_TUN_1":   ESP algorithms loaded: 3DES(3)_192-MD5(1)_128
000 "IPSec_TUN_1":   ESP algorithm newest: 3DES_192-HMAC_MD5; pfsgroup=<N/A>
000 
000 #2: "IPSec_TUN_1":500 STATE_PARENT_I3 (PARENT SA established); EVENT_SA_REPLACE in 27814s; newest IPSEC; eroute owner; nodpd; idle; import:admin initiate
000 #1: "IPSec_TUN_1":500 STATE_PARENT_I3 (PARENT SA established); EVENT_SA_REPLACE in 86322s; newest ISAKMP; nodpd; idle; import:admin initiate
000 

/etc # /usr/scripts/ipsec status
IPsec running  - pluto pid: 3264
pluto pid 3264
No tunnels up

/etc # ip xfrm policy
src 192.168.0.0/24 dst 192.168.80.0/24 
        dir out priority 2344 
        tmpl src 172.16.99.120 dst 172.16.5.245
                proto esp reqid 16385 mode tunnel
src 192.168.80.0/24 dst 192.168.0.0/24 
        dir fwd priority 2344 
        tmpl src 172.16.5.245 dst 172.16.99.120
                proto esp reqid 16385 mode tunnel
src 192.168.80.0/24 dst 192.168.0.0/24 
        dir in priority 2344 
        tmpl src 172.16.5.245 dst 172.16.99.120
                proto esp reqid 16385 mode tunnel
src 0.0.0.0/0 dst 0.0.0.0/0 
        socket out priority 0 

/etc # ip xfrm state 
src 172.16.5.245 dst 172.16.99.120
        proto esp spi 0x81302d8a reqid 16385 mode tunnel
        replay-window 32 flag af-unspec
        auth-trunc hmac(md5) 0x66087aa2b73c882055863b308df72e1d 96
        enc cbc(des3_ede) 0x5753aecfc16e3faaf0ed7758bb3a80740a1aadc735d6bbb1
src 172.16.99.120 dst 172.16.5.245
        proto esp spi 0x7bb07847 reqid 16385 mode tunnel
        replay-window 32 flag af-unspec
        auth-trunc hmac(md5) 0x57d8ce7cd6c5531574eebdd0d0d35ec5 96
        enc cbc(des3_ede) 0x127dcce6e88de74a21cfb86fd4152f03075070c69eb9b5f6

**Comment by letoams** [comment]
On Fri, 7 Apr 2017, somme8023 wrote:

> With the following configuration, the tunnel can not get up.Why?

Your tunnel came up according to your logs, despite the bad message
from the init script's status command (an openswan bug)

If you don't see traffic flow, you have another issue. Try "ipsec
verify".

On libreswan, you can use "ipsec whack --trafficstatus" to get a clear
idea of which tunnels are up and how much traffic these passed.

Paul

**Comment by somme8023** [comment]
@letoams Ikev1, the tunnel can get up. When the configuration of the IKEv2, the tunnel does not come. I would like to ask, what need to configure IKEv2?

**Comment by somme8023** [comment]
@letoams Because the device does not have a Perl environment, can not use “ipsec verify”.

**Comment by letoams** [comment]
On Sat, 8 Apr 2017, somme8023 wrote:

> @letoams Ikev1, the tunnel can get up. When the configuration of the IKEv2, the tunnel does not come. I would like to ask, what need to configure IKEv2?

openswan's IKEv2 implementation is pretty broken. I would not recommend
it. Try libreswan if you need IKEv2, or stick with openswan's IKEv1.

Paul

**Comment by shussain** [comment]
> openswan's IKEv2 implementation is pretty broken.

I would have to push back a bit on that.  :)            

Like all software there are bugs in Openswan but I wouldn't say Openswan's IKEv2 implementation is broken. 

There are some known bugs with IKEv2 in 2.6.42 which have seen subsequently been fixed. This is why, I would recommend to @somme8023  to try the latest version of Openswan (2.6.49) which has severa;IKEv2 related bug fixes. If there are still some issues, we would be happy to investigate it further.

**Comment by letoams** [comment]
On Sat, 8 Apr 2017, Samir wrote:

>       openswan's IKEv2 implementation is pretty broken.
> 
> I would have to push back a bit on that. :)
> 
> Like all software there are bugs in Openswan but I wouldn't say Openswan's IKEv2 implementation is broken.

I understand you feel that way. I have been fixing and extending the
IKEv2 code since the project was forced to rename from openswan into
libreswan, and I know the massive amount of code changes that were needed
to attain USGv6 and TAHI test suite compliance for IKEv2. You can also
try to run the libreswan IKEv2 tests using openswan to confirm some of
these issues. You can check the libreswan CHANGES file for all the work
done to IKEv2.

**Comment by shussain** [comment]
Thank you for the tip about attaining USGv6 and TAHI test suite compliance with IKEv2. And using the libreswan IKEv2 tests. I have made a note of that and appreciate the feedback. I will also look at the libreswan CHANGES file for IKEv2 changes/fixes that we should implement

As you have noted, our respective codebases have diverged. While there is likely some shared bugs, @mcr has made quite a lot of commits to our IKEv2 implementation, and we have been making use of IPv6 more in our test environment. While there is always room for improvement, I feel our changes have been sufficient that I would disagree with the statement that Openswan's IKEv2 implementation is broken.

If you are aware of any major flaws IKEv2 in the latest version of Openswan, we would be happy to investigate it further and work on it.

**Comment by somme8023** [comment]
@letoams What’s the differences between Openswan and Libreswan ?

**Comment by somme8023** [comment]
@shussain @letoams Later, I used the  version of Openswan (2.6.48),the tunnel still can't get up.But sub network equipment PING packet test, from the capture of the message is ESP message

**Comment by letoams** [comment]
See https://nohats.ca/wordpress/libreswan/ and https://nohats.ca/wordpress/openswan/

That lawsuit is why openswan was renamed to libreswan and why libreswan replaced openswan in fedora, centos, rhel and Debian.

**Comment by shussain** [comment]
@somme8023    So it seems the packet is getting sent. Do the logs show anything? You can increase your log verbosity in your /etc/ipsec.conf

Similarly, do you have access to the Ciso side?  Can you see what it's log are showing?

**Comment by somme8023** [comment]
@shussain Today, I used the version of Openswan (2.6.49.1) , he tunnel can not get up. From the log information, the created SA was deleted

log:
pluto[1032]: Starting Pluto (Openswan Version 2.6.49.1; Vendor ID OSWhKaciWM}g) pid:1032
pluto[1032]: LEAK_DETECTIVE support [disabled]
pluto[1032]: OCF support for IKE [disabled]
pluto[1032]: SAref support [disabled]: Protocol not available
pluto[1032]: SAbind support [disabled]: Protocol not available
pluto[1032]: NSS support [disabled]
pluto[1032]: HAVE_STATSD notification support not compiled in
pluto[1032]: Setting NAT-Traversal port-4500 floating to on
pluto[1032]:    port floating activation criteria nat_t=1/port_float=1
pluto[1032]:    NAT-Traversal support  [enabled]
pluto[1032]: using /dev/urandom as source of random entropy
pluto[1032]: ike_alg_register_enc(): Activating OAKLEY_AES_CBC: Ok (ret=0)
pluto[1032]: ike_alg_register_hash(): Activating OAKLEY_SHA2_512: Ok (ret=0)
pluto[1032]: ike_alg_register_hash(): Activating OAKLEY_SHA2_256: Ok (ret=0)
pluto[1032]: starting up 1 cryptographic helpers
pluto[1032]: started helper pid=1037 (fd:7)
pluto[1032]: Using Linux XFRM/NETKEY IPsec interface code on 3.10.49
pluto[1037]: using /dev/urandom as source of random entropy
pluto[1032]: ike_alg_register_enc(): Activating aes_ccm_8: Ok (ret=0)
pluto[1032]: ike_alg_add(): ERROR: algo_type '0', algo_id '0', Algorithm type already exists
pluto[1032]: ike_alg_register_enc(): Activating aes_ccm_12: FAILED (ret=-17)
pluto[1032]: ike_alg_add(): ERROR: algo_type '0', algo_id '0', Algorithm type already exists
pluto[1032]: ike_alg_register_enc(): Activating aes_ccm_16: FAILED (ret=-17)
pluto[1032]: ike_alg_add(): ERROR: algo_type '0', algo_id '0', Algorithm type already exists
pluto[1032]: ike_alg_register_enc(): Activating aes_gcm_8: FAILED (ret=-17)
pluto[1032]: ike_alg_add(): ERROR: algo_type '0', algo_id '0', Algorithm type already exists
pluto[1032]: ike_alg_register_enc(): Activating aes_gcm_12: FAILED (ret=-17)
pluto[1032]: ike_alg_add(): ERROR: algo_type '0', algo_id '0', Algorithm type already exists
pluto[1032]: ike_alg_register_enc(): Activating aes_gcm_16: FAILED (ret=-17)
pluto[1032]: adding connection: "IPSec_TUN_1"
pluto[1032]: listening for IKE messages
pluto[1032]: adding interface lan0/lan0 192.168.0.1:500 (AF_INET)
pluto[1032]: adding interface lan0/lan0 192.168.0.1:4500
pluto[1032]: adding interface wan/wan 172.16.99.120:500 (AF_INET)
pluto[1032]: adding interface wan/wan 172.16.99.120:4500
pluto[1032]: adding interface lo/lo 127.0.0.1:500 (AF_INET)
pluto[1032]: adding interface lo/lo 127.0.0.1:4500
pluto[1032]: loading secrets from "/etc/ipsec.secrets"
pluto[1032]: | creating SPD to 172.16.99.120->spi=00000104@0.0.0.0 proto=61
pluto[1032]: | creating SPD to 172.16.99.120->spi=00000104@0.0.0.0 proto=61
pluto[1032]: "IPSec_TUN_1" #1: initiating v2 parent SA
pluto[1032]: "IPSec_TUN_1" #1: STATE_PARENT_I1: initiate
pluto[1032]: "IPSec_TUN_1" #1: transition from state STATE_IKEv2_START to state STATE_PARENT_I1
pluto[1032]: "IPSec_TUN_1" #1: STATE_PARENT_I1: sent v2I1, expected v2R1 (msgid: 00000000)
pluto[1032]: "IPSec_TUN_1" #2: transition from state STATE_PARENT_I1 to state STATE_PARENT_I2
pluto[1032]: "IPSec_TUN_1" #2: STATE_PARENT_I2: sent v2I2, expected v2R2 {auth=IKEv2 cipher=oakley_3des_cbc_192 integ=md5_96 prf=oakley_md5 group=modp1024} (msgid: 00000001)
pluto[1032]: packet from 172.16.5.245:500: IKEv2 mode peer ID is ID_IPV4_ADDR: '172.16.5.245'
pluto[1032]: | checking TSi(1)/TSr(1) selectors, looking for exact match
pluto[1032]: | printing contents struct traffic_selector
pluto[1032]: |   ts_type: IKEv2_TS_IPV4_ADDR_RANGE
pluto[1032]: |   ipprotoid: 0
pluto[1032]: |   startport: 0
pluto[1032]: |   endport: 65535
pluto[1032]: |   ip low: 192.168.0.0
pluto[1032]: |   ip high: 192.168.0.255
pluto[1032]: | printing contents struct traffic_selector
pluto[1032]: |   ts_type: IKEv2_TS_IPV4_ADDR_RANGE
pluto[1032]: |   ipprotoid: 0
pluto[1032]: |   startport: 0
pluto[1032]: |   endport: 65535
pluto[1032]: |   ip low: 192.168.80.0
pluto[1032]: |   ip high: 192.168.80.255
pluto[1032]: | creating SPD to 172.16.5.245->spi=00000100@172.16.99.120 proto=4
pluto[1032]: | creating SPD to 172.16.99.120->spi=00000000@172.16.5.245 proto=4
pluto[1032]: "IPSec_TUN_1" #2: transition from state STATE_PARENT_I2 to state STATE_CHILD_C1_KEYED
pluto[1032]: "IPSec_TUN_1" #2: negotiated tunnel [192.168.0.0,192.168.0.255 proto:0 port:0-65535] -> [192.168.80.0,192.168.80.255 proto:0 port:0-65535]
pluto[1032]: "IPSec_TUN_1" #2: STATE_CHILD_C1_KEYED: CHILD SA established tunnel mode {ESP=>0x1e69cd92 <0x50817c56 xfrm=3DES_192-HMAC_MD5 NATOA=none NATD=none DPD=none} (msgid: 00000001)
pluto[1032]: | releasing whack for #2 (sock=-1)
pluto[1032]: | releasing whack for #1 (sock=-1)
[   26.528000] lan0: port 1(eth1) entered forwarding state
pluto[1032]: pending Quick Mode with 172.16.5.245 "IPSec_TUN_1" took too long -- replacing phase 1
pluto[1032]: "IPSec_TUN_1" #1: deleting state #1 (STATE_PARENT_I3)
pluto[1032]: "IPSec_TUN_1" #3: starting rekey of CHILD SA for state=#2 (expired) using PARENT SA #1
pluto[1032]: "IPSec_TUN_1" #3: transition from state STATE_CHILD_C1_REKEY to state STATE_CHILD_C1_REKEY
pluto[1032]: "IPSec_TUN_1" #3: STATE_CHILD_C1_REKEY: CHILD SA being rekeyed (msgid: 00000002)
# _pluto[1032]: packet from 172.16.5.245:500: deleting state #3 (STATE_CHILDSA_DEL)
pluto[1032]: packet from 172.16.5.245:500: deleting state #2 (STATE_CHILDSA_DEL)_
pluto[1032]: | creating SPD to 172.16.99.120->spi=00000104@0.0.0.0 proto=61
pluto[1032]: | creating SPD to 172.16.5.245->spi=00000100@172.16.99.120 proto=255
pluto[1032]: packet from 172.16.5.245:500: deleting state #1 (STATE_IKESA_DEL)
pluto[1032]: pending Quick Mode with 172.16.5.245 "IPSec_TUN_1" took too long -- replacing phase 1

**Comment by somme8023** [comment]
@shussain May be because I set on CISCO router‘s NAT keepalive, resulting in SA was deleted.

**Comment by somme8023** [comment]
@shussain What will be the impact of the IPSec tunnel no up?

**Comment by shussain** [comment]
@somme8023. The log show you established a proper IKEv2 connection. But then it seemed to time out.

Can you enable further logging? While it would container a lot of info,  perhaps you should temporarily set:
plutodebug=all

Does the Cisco side have any useful info?

**Comment by somme8023** [comment]
@shussain Thank you. I'll do it your way. No useful information was found on Cisco side.
For IKEv2, if you want to use radius, how does ipsec.conf and ipsec.secrets need to be configured?

**Comment by shussain** [comment]
In regards to using Radius, here are some guides you can refer to:

https://www.debuntu.org/how-to-set-up-a-l2tp-over-ipsec-vpn-using-a-radius-backend/
https://www.howtoforge.com/tutorial/l2tp-over-ipsec-using-openswan-with-freeradius-authentication/

**Comment by somme8023** [comment]
@shussain The problem has been solved. The tunnel is ok. Use the command "IPSec status" to call the "_realsetup" script, which is a bit of a problem.
In IKEv2,IKE SA is still known as IKE SA, and IPSec SA is called CHILD SA.

When configured as IKEv2, there is no "IPSec SA established" in the output information of `ipsec auto --status", only "CHILD SA established". Using "IPSec status" command, because the "IPSec SA established" string could not be found, prompt "No tunnels up".


_realsetup:
	if test -r /proc/net/ipsec_eroute
	then
		eroutes=`wc -l < /proc/net/ipsec_eroute 2> /dev/null | sed s/\ //g`
	else
		# eroutes=`ipsec auto --status 2> /dev/null | grep -c -i "ipsec sa established"`
	fi


Hope to modify this BUG.

**Comment by shussain** [comment]
Thank you @somme8023    You are correct there is a bug. it has been fixed in the 2.6.50dev branch and will be in the next release.
